name: RO Crate to GitHub Pages
on:
  push:
    branches:
      - master
      - workflow-only
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    concurrency: ci-${{github.ref}}
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install ro-crate-html-js
        run: |
          mkdir /node_modules
          npm install --prefix /node_modules ro-crate-html-js

      - name : Make RO Crate Preview
        run: ln -sf ro-crate-preview.html index.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
